### ISSUE TITLE
help

### ISSUE THREAD

**Issue by lanjiachuan** [muaz-khan/cordova-mobile-apps#3]
The author: hello!Thank you for your help, I have a problem need to consult you for a minute, I'm in Java development, for the node. Js is not very understand, don't know how to integrate your server to my Java environment, my Java environment using nettysocket. IO I wonder if you could help on this issue

**Comment by muaz-khan** [comment]
Though RTCMultiConnection can easily adopt any 3rd party signaling server implementation. However personally I prefer the built-in socket.io. I recommend this procedure:
1. Install [RTCMultiConnection-Server](https://github.com/muaz-khan/RTCMultiConnection-Server) on heroku or any 3rd party nodejs hosting
2. Now you only need to set this property in your javascript codes: [`connection.socketURL`](https://www.rtcmulticonnection.org/docs/socketURL/)

It doesn't matters if you're using a cordova/ionic application or HTML code inside angular/vue or java/python. It will work in all cases. Angular is kind of tricky because it requires `SocketConnection` to be copied/pasted in the same directory; however PHP/Java should not require any further changes or modifications or tricks.

Please try above procedure i.e. run socket.io on separate port or ip-address or hosting; and use it using `socketURL` property.

**Comment by lanjiachuan** [comment]
Author: hello, thank you for your help again, and I think the current demand is set up a video chat system, have the function of video conference system at the same time, if I use your this system, I should how to set up a complete environment, such as what I need to install the service, to achieve a goal
